# https://taskfile.dev

version: '3'

tasks:
  setup:
    desc: Create required directories
    cmds:
      - mkdir -p dist

  build:
    desc: Build the Go application
    deps: [setup]
    cmds:
      - go build -o dist/rayt main.go color.go vec3.go ray.go

  generate:
    desc: Generate the PPM image in the dist folder
    deps: [build]
    cmds:
      - ./dist/rayt > ./dist/image.ppm 
    
  default:
    desc: Run the complete workflow - build and generate image
    deps: [generate]